# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - cambiazo-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Create firebase-key.json from secret
        run: |
          mkdir -p src/main/resources/config
          echo "${{ secrets.FIREBASE_KEY_JSON }}" > src/main/resources/config/firebase-key.json

      - name: Build with Maven
        env:
          DB_URL: jdbc:mysql://cambiazoserver.mysql.database.azure.com:3306/cambiazomovil?allowPublicKeyRetrieval=true&useSSL=true
          DB_USERNAME: cambiazoserver
          DB_PASSWORD: techZomovil2024
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4E74FD4F95D04B39A83F2474831D77DE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2176E7DF88374AF3996F88C185CE5905 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D13063B9E33640E8B7D87B7E452C5510 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cambiazo-backend'
          slot-name: 'Production'
          package: '*.jar'
